services:
  jenkins-blueocean:
    image: myjenkins-blueocean
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # Point Jenkins to the Docker socket
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=0
      - TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock # For Testcontainers to use the host's Docker socket
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:
    external: true

volumes:
  jenkins-data:
  jenkins-docker-certs:
